In [ ]:
from datetime import date

mahasiswa = [
    {
        "Nama": "Amos",
        "NIM": "2022071020",
        "Prodi": "Informatika",
        "Mata Kuliah": "Desain Ana;isis Algoritma",
        "Tanggal Hari Ini": date.today().strftime("%Y-%m-%d"),
        "Nama Universitas": "Universitas Pembangunan Jaya"
    },
]

for mhs in mahasiswa:
    print("Nama:", mhs["Nama"])
    print("NIM:", mhs["NIM"])
    print("Prodi:", mhs["Prodi"])
    print("Mata Kuliah:", mhs["Mata Kuliah"])
    print("Tanggal Hari Ini:", mhs["Tanggal Hari Ini"])
    print("Nama Universitas:", mhs["Nama Universitas"])
    print("\n")

Nama: Amos
NIM: 2022071020
Prodi: Informatika
Mata Kuliah: Desain Ana;isis Algoritma
Tanggal Hari Ini: 2023-09-13
Nama Universitas: Universitas Pembangunan Jaya




In [ ]:
bin_colors=['Red','Green','Blue','Yellow']
bin_colors[1]

'Green'

In [ ]:
from datetime import date

mahasiswa=['Nama : Amos',
        'NIM : 2022071020',
        'Prodi : Informatika',
        'Mata Kuliah : Desain Analisis Algoritma',
        'Tanggal Hari Ini : ', date.today().strftime("%Y-%m-%d"),
        'Nama Universitas : Universitas Pembangunan Jaya']

mahasiswa[1]

'NIM : 2022071020'

In [ ]:
from datetime import date

mahasiswa=['Nama : Amos',
        'NIM : 2022071020',
        'Prodi : Informatika',
        'Mata Kuliah : Desain Analisis Algoritma',
        'Tanggal Hari Ini : ', date.today().strftime("%Y-%m-%d"),
        'Nama Universitas : Universitas Pembangunan Jaya']

mahasiswa[-1]

'Nama Universitas : Universitas Pembangunan Jaya'

In [ ]:
bin_colors=['Red','Green','Blue','Yellow']
bin_colors[1:4]

['Green', 'Blue', 'Yellow']

In [ ]:
from datetime import date

mahasiswa=['Nama : Amos',
        'NIM : 2022071020',
        'Prodi : Informatika',
        'Mata Kuliah : Desain Analisis Algoritma',
        'Tanggal Hari Ini : ', date.today().strftime("%Y-%m-%d"),
        'Nama Universitas : Universitas Pembangunan Jaya']

mahasiswa[1:3]

['NIM : 2022071020', 'Prodi : Informatika']

In [ ]:
bin_colors=['Red','Green','Blue','Yellow']
for aColor in bin_colors:
  print(aColor + " Square")

Red Square
Green Square
Blue Square
Yellow Square


In [ ]:
from datetime import date

mahasiswa=['Nama : Amos',
        'NIM : 2022071020',
        'Prodi : Informatika',
        'Mata Kuliah : Desain Analisis Algoritma',
        'Tanggal Hari Ini : ', date.today().strftime("%Y-%m-%d"),
        'Nama Universitas : Universitas Pembangunan Jaya']

for a in mahasiswa:
  print( "UPJ " + a)

UPJ Nama : Amos
UPJ NIM : 2022071020
UPJ Prodi : Informatika
UPJ Mata Kuliah : Desain Analisis Algoritma
UPJ Tanggal Hari Ini : 
UPJ 2023-09-13
UPJ Nama Universitas : Universitas Pembangunan Jaya


In [ ]:
bin_colors=['Red','Green','Blue','Yellow']
bin_colors[2:]

['Blue', 'Yellow']

In [ ]:
UPJ=['Universitas','Pembangunan','Jaya']
UPJ[1:]

['Pembangunan', 'Jaya']

In [ ]:
nested_tuple1=["100"]
nested_tuple2=["200","400","600"]
nested_tuple3=["300"]
nested_tuple4=["400","800"]

nested_tuple=(nested_tuple1 ,nested_tuple2 ,nested_tuple3 ,nested_tuple4)
print(nested_tuple)

(['100'], ['200', '400', '600'], ['300'], ['400', '800'])


In [ ]:
bin_colors={
    "manual_color" : "Yellow",
    "approved_color" : "Green",
    "refused_color" : "Red"
}
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [ ]:
bin_colors={
    "manual_color" : "Yellow",
    "approved_color" : "Green",
    "refused_color" : "Red"
}
bin_colors.get('approved_color')

'Green'

In [ ]:
bin_colors={
    "manual_color" : "Yellow",
    "approved_color" : "Green",
    "refused_color" : "Red"
}
bin_colors['approved_color']="Purple"
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Purple', 'refused_color': 'Red'}


In [ ]:
data={
    "Nama" : "Amos Immanuel Sihombing",
    "Nim" : "2022071020",
    "Prodi Universitas" : "Teknik Informatika"
}
data.get('Nim')

'2022071020'

In [ ]:
data={
    "Nama" : "Amos Immanuel Sihombing",
    "Nim" : "2022071020",
    "Prodi Universitas" : "Teknik Informatika"
}
data['Nim']="berubah"
print(data)

{'Nama': 'Amos Immanuel Sihombing', 'Nim': 'berubah', 'Prodi Universitas': 'Teknik Informatika'}


In [1]:
import pandas as pd

data={'satu': [1,1,1,1,1],
    'dua': [2,2,2,2,2],
    'tiga': [3,3,3,3,3]}

df=pd.DataFrame(data, index=['a','b','c','d','e'])
df.Head()

AttributeError: ignored

In [4]:
import numpy as np

matrix = np.array([
    [100,200,300],
    [700,600,500],
    [900,1000,800]
])

print(matrix)

print("\nTranspose:")
print(matrix.T)

[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]

Transpose:
[[ 100  700  900]
 [ 200  600 1000]
 [ 300  500  800]]
